[04-Jul-2023 09:48:28 Asia/Tehran] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 5.6.40. in /home3/fckujelw/public_html/vendor/composer/platform_check.php on line 25
[04-Jul-2023 09:49:20 Asia/Tehran] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.13. in /home3/fckujelw/public_html/vendor/composer/platform_check.php on line 24
[04-Jul-2023 09:50:22 Asia/Tehran] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.13. in /home3/fckujelw/public_html/vendor/composer/platform_check.php on line 24
[04-Jul-2023 09:50:23 Asia/Tehran] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.13. in /home3/fckujelw/public_html/vendor/composer/platform_check.php on line 24
[04-Jul-2023 09:54:07 Asia/Tehran] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.13. in /home3/fckujelw/public_html/vendor/composer/platform_check.php on line 24
[04-Jul-2023 10:05:02 Asia/Tehran] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 5.6.40. in /home3/fckujelw/public_html/vendor/composer/platform_check.php on line 25
[04-Jul-2023 10:18:03 Asia/Tehran] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 5.6.40. in /home3/fckujelw/public_html/vendor/composer/platform_check.php on line 25
[04-Jul-2023 10:19:02 Asia/Tehran] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.13. in /home3/fckujelw/public_html/vendor/composer/platform_check.php on line 24
[04-Jul-2023 07:42:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
[04-Jul-2023 07:43:39 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
[29-Jul-2023 10:10:13 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
[14-Aug-2023 06:07:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
[14-Aug-2023 06:08:15 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
[14-Aug-2023 06:08:35 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
[14-Aug-2023 09:15:39 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
[15-Aug-2023 19:54:35 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
[16-Aug-2023 06:19:34 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:264
Stack trace:
#0 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home3/fckujelw...', 264, 5)
#1 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#2 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/traces.html.php(52): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#4 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception.html.php(57): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#6 /home3/fckujelw/public_html/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(342): include('/home3/fckujelw...')
#8 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(148): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(74): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(612): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(586): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(567): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(546): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home3/fckujelw/public_html/app/Exceptions/Handler.php(74): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#18 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#19 /home3/fckujelw/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#20 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#21 {main}
  thrown in /home3/fckujelw/public_html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 264
